### ISSUE TITLE
Everything on the main page is inside a jumbotron

### ISSUE THREAD

**Issue by tgaff** [isangieri/project-01#2]
This is not really what the jumbotron is intended for.  Is there something specific you were trying to accomplish with this?

**Comment by tgaff** [comment]
<img width="637" alt="screen shot 2015-12-18 at 12 14 21 pm" src="https://cloud.githubusercontent.com/assets/1916144/11906385/f1d219ba-a580-11e5-9c05-81b940531b37.png">

**Comment by a-n-g-i-e-r-i** [comment]
Changed jumbotron elements to a new class called .large-box.
