### ISSUE TITLE
consume eviction api on server-side

### ISSUE THREAD

**Issue by nathanallen** [isangieri/project-01#3]
You're doing a lot of heavy lifting client-side (mashup of eviction API + google maps + your own endpoints )! Can you move it server-side to speed things up?

Reference: https://github.com/request/request

**Comment by a-n-g-i-e-r-i** [comment]
Used Request to make server side get request to SF Open Data, filtering useful attributes from the JSON object (including an image url concatenated using SF Open Data coordinate attribute) into the eviction mongodb model, using Request post method.
