### ISSUE TITLE
Add jQuery datePicker and/or date validation

### ISSUE THREAD

**Issue by tgaff** [isangieri/project-01#5]
I just submitted a notice in the future.  You could probably pretty quickly make sure the date is less than or equal to Date.now()

**Comment by a-n-g-i-e-r-i** [comment]
Added separate Event Date and a Notice Date elements to the notice.js model. Event Date is a user selected date (using date picker) to choose the date associated with the content of the notice (when a document/communication/information was received). The Notice Date is a timestamp for the posting of the notice.
