### ISSUE TITLE
Error on initial page load: Cannot read property 'latitude' of undefined

### ISSUE THREAD

**Issue by tgaff** [isangieri/project-01#6]
visit the main page on heroku 
in the browser console

<img width="960" alt="screen shot 2015-12-18 at 12 22 57 pm" src="https://cloud.githubusercontent.com/assets/1916144/11906560/4cfa1738-a582-11e5-9ffb-ed570f4522e7.png">

**Comment by a-n-g-i-e-r-i** [comment]
Yup. Heather and I never figured out what that was. The item in question does what I ask it to do, so I left it.

**Comment by a-n-g-i-e-r-i** [comment]
Fixed the bug. The incoming JSON required parsing before the 'latitude' attribute could be readable.
